In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4190, 4937, 4316, 5186],
 [4190, 4937, 4316, 8574],
 [4190, 8083, 4316, 6047],
 [4354, 4946, 2810, 4004, 5030],
 [4354, 4946, 2810, 4004, 3198],
 [1553, 4190, 3651, 4316, 234],
 [2405, 5233, 2198, 4004]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4190 4937 4316 5186]
 [   0    0    0    0 4190 4937 4316 8574]
 [   0    0    0    0 4190 8083 4316 6047]
 [   0    0    0 4354 4946 2810 4004 5030]
 [   0    0    0 4354 4946 2810 4004 3198]
 [   0    0    0 1553 4190 3651 4316  234]
 [   0    0    0    0 2405 5233 2198 4004]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

e:\ann\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step


array([[[-5.2349642e-04, -1.6201127e-02,  1.0274433e-02, -4.7660746e-02,
          1.8253651e-02, -2.5549842e-02, -2.3433590e-02,  4.9263146e-02,
         -2.2939121e-02,  3.0990843e-02],
        [-5.2349642e-04, -1.6201127e-02,  1.0274433e-02, -4.7660746e-02,
          1.8253651e-02, -2.5549842e-02, -2.3433590e-02,  4.9263146e-02,
         -2.2939121e-02,  3.0990843e-02],
        [-5.2349642e-04, -1.6201127e-02,  1.0274433e-02, -4.7660746e-02,
          1.8253651e-02, -2.5549842e-02, -2.3433590e-02,  4.9263146e-02,
         -2.2939121e-02,  3.0990843e-02],
        [-5.2349642e-04, -1.6201127e-02,  1.0274433e-02, -4.7660746e-02,
          1.8253651e-02, -2.5549842e-02, -2.3433590e-02,  4.9263146e-02,
         -2.2939121e-02,  3.0990843e-02],
        [ 3.6763284e-02, -2.0220995e-02,  1.9906785e-02,  7.1660988e-03,
          3.8370755e-02, -2.1592522e-02,  1.4284346e-02, -1.0077991e-02,
          1.3437916e-02, -2.0252896e-02],
        [ 4.2588126e-02, -1.8604875e-02, -2.0694733e-03,  4.

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4190, 4937, 4316, 5186], dtype=int32)

In [18]:
model.predict(embedded_docs[0:1])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([[[-0.0005235 , -0.01620113,  0.01027443, -0.04766075,
          0.01825365, -0.02554984, -0.02343359,  0.04926315,
         -0.02293912,  0.03099084],
        [-0.0005235 , -0.01620113,  0.01027443, -0.04766075,
          0.01825365, -0.02554984, -0.02343359,  0.04926315,
         -0.02293912,  0.03099084],
        [-0.0005235 , -0.01620113,  0.01027443, -0.04766075,
          0.01825365, -0.02554984, -0.02343359,  0.04926315,
         -0.02293912,  0.03099084],
        [-0.0005235 , -0.01620113,  0.01027443, -0.04766075,
          0.01825365, -0.02554984, -0.02343359,  0.04926315,
         -0.02293912,  0.03099084],
        [ 0.03676328, -0.02022099,  0.01990679,  0.0071661 ,
          0.03837075, -0.02159252,  0.01428435, -0.01007799,
          0.01343792, -0.0202529 ],
        [ 0.04258813, -0.01860487, -0.00206947,  0.04622204,
          0.01923865,  0.03393287,  0.00398147, -0.00752421,
          0.02857903, -0.04048625],
        [-0.04863656,  0.03631147,  0.0178666 ,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 4190, 4937, 4316, 5186], dtype=int32)